[default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@jbx-protocol/=node_modules/@jbx-protocol/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@contracts=contracts/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config